-- 50 distritos del ámbito MVP: Lima Metropolitana (43) + Callao (7)
-- Ubigeos oficiales INEI

INSERT INTO distrito (ubigeo, departamento, provincia, distrito, ambito_mvp) VALUES
-- Lima Metropolitana (Departamento 15, Provincia 1501)
('150101', 'LIMA', 'LIMA', 'LIMA',                       TRUE),
('150102', 'LIMA', 'LIMA', 'ANCON',                      TRUE),
('150103', 'LIMA', 'LIMA', 'ATE',                        TRUE),
('150104', 'LIMA', 'LIMA', 'BARRANCO',                   TRUE),
('150105', 'LIMA', 'LIMA', 'BREÑA',                      TRUE),
('150106', 'LIMA', 'LIMA', 'CARABAYLLO',                 TRUE),
('150107', 'LIMA', 'LIMA', 'CHACLACAYO',                 TRUE),
('150108', 'LIMA', 'LIMA', 'CHORRILLOS',                 TRUE),
('150109', 'LIMA', 'LIMA', 'CIENEGUILLA',                TRUE),
('150110', 'LIMA', 'LIMA', 'COMAS',                      TRUE),
('150111', 'LIMA', 'LIMA', 'EL AGUSTINO',                TRUE),
('150112', 'LIMA', 'LIMA', 'INDEPENDENCIA',              TRUE),
('150113', 'LIMA', 'LIMA', 'JESUS MARIA',                TRUE),
('150114', 'LIMA', 'LIMA', 'LA MOLINA',                  TRUE),
('150115', 'LIMA', 'LIMA', 'LA VICTORIA',                TRUE),
('150116', 'LIMA', 'LIMA', 'LINCE',                      TRUE),
('150117', 'LIMA', 'LIMA', 'LOS OLIVOS',                 TRUE),
('150118', 'LIMA', 'LIMA', 'LURIGANCHO',                 TRUE),
('150119', 'LIMA', 'LIMA', 'LURIN',                      TRUE),
('150120', 'LIMA', 'LIMA', 'MAGDALENA DEL MAR',          TRUE),
('150121', 'LIMA', 'LIMA', 'PUEBLO LIBRE',               TRUE),
('150122', 'LIMA', 'LIMA', 'MIRAFLORES',                 TRUE),
('150123', 'LIMA', 'LIMA', 'PACHACAMAC',                 TRUE),
('150124', 'LIMA', 'LIMA', 'PUCUSANA',                   TRUE),
('150125', 'LIMA', 'LIMA', 'PUENTE PIEDRA',              TRUE),
('150126', 'LIMA', 'LIMA', 'PUNTA HERMOSA',              TRUE),
('150127', 'LIMA', 'LIMA', 'PUNTA NEGRA',                TRUE),
('150128', 'LIMA', 'LIMA', 'RIMAC',                      TRUE),
('150129', 'LIMA', 'LIMA', 'SAN BARTOLO',                TRUE),
('150130', 'LIMA', 'LIMA', 'SAN BORJA',                  TRUE),
('150131', 'LIMA', 'LIMA', 'SAN ISIDRO',                 TRUE),
('150132', 'LIMA', 'LIMA', 'SAN JUAN DE LURIGANCHO',     TRUE),
('150133', 'LIMA', 'LIMA', 'SAN JUAN DE MIRAFLORES',     TRUE),
('150134', 'LIMA', 'LIMA', 'SAN LUIS',                   TRUE),
('150135', 'LIMA', 'LIMA', 'SAN MARTIN DE PORRES',       TRUE),
('150136', 'LIMA', 'LIMA', 'SAN MIGUEL',                 TRUE),
('150137', 'LIMA', 'LIMA', 'SANTA ANITA',                TRUE),
('150138', 'LIMA', 'LIMA', 'SANTA MARIA DEL MAR',        TRUE),
('150139', 'LIMA', 'LIMA', 'SANTA ROSA',                 TRUE),
('150140', 'LIMA', 'LIMA', 'SANTIAGO DE SURCO',          TRUE),
('150141', 'LIMA', 'LIMA', 'SURQUILLO',                  TRUE),
('150142', 'LIMA', 'LIMA', 'VILLA EL SALVADOR',          TRUE),
('150143', 'LIMA', 'LIMA', 'VILLA MARIA DEL TRIUNFO',    TRUE),
-- Provincia Constitucional del Callao (Departamento 07, Provincia 0701)
('070101', 'CALLAO', 'CALLAO', 'CALLAO',                    TRUE),
('070102', 'CALLAO', 'CALLAO', 'BELLAVISTA',                TRUE),
('070103', 'CALLAO', 'CALLAO', 'CARMEN DE LA LEGUA REYNOSO',TRUE),
('070104', 'CALLAO', 'CALLAO', 'LA PERLA',                  TRUE),
('070105', 'CALLAO', 'CALLAO', 'LA PUNTA',                  TRUE),
('070106', 'CALLAO', 'CALLAO', 'VENTANILLA',                TRUE),
('070107', 'CALLAO', 'CALLAO', 'MI PERU',                   TRUE)
ON CONFLICT (ubigeo) DO NOTHING;
